### ISSUE TITLE
Clicking Play just opens Spotify App

### ISSUE THREAD

**Issue by Jalsemgeest** [alexanderwallin/react-spotify-player#1]
Hi,

I was wondering if the intended purpose of the react spotify player was to just display a playlist, or what?

It seems when I added the code you have within this repo it showed up properly, although upon clicking the Play button it just opened up the Spotify app.

Suggestions?

**Comment by Jalsemgeest** [comment]
I'm getting this error in the console:

`Uncaught (in promise) Object {type: "4110", message: "No user logged in"}`

**Comment by alexanderwallin** [comment]
Hi @Jalsemgeest!

The intended purpose is to simply embed the [Spotify Play Button](https://developer.spotify.com/technologies/widgets/spotify-play-button/). It's behaviour is determined by Spotify.

Default behaviour should be to play a song if you have Spotify running. Judging by your error it sounds like you're not logged in to Spotify.
