### ISSUE TITLE
Warning when using deprecated PropTypes from the react package

### ISSUE THREAD

**Issue by martin-eq** [alexanderwallin/react-spotify-player#3]
Fix this warning:
`Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs`

I'm going to create a PR for this.

**Comment by alexanderwallin** [comment]
Please do, Martin! I'll merge it in and publish a new version ASAP.

**Comment by alexanderwallin** [comment]
Resolved in #4
